"""Per-role action sequence templates, with per-host overrides.

The Excel plan models "Stop application Group N" and "Start application Group N" as two
*separate* steps, often far apart in time and gated by their own (possibly cross-team)
dependencies - the OS patching itself happens between them, outside this tool. So each
role exposes a STOP half and a START half independently, rather than one bundled
stop->patch->start sequence:

  - stop_pre_group:    once per group, before any node's stop_per_node runs (e.g. cluster-
                       wide captain transfer to the other site).
  - stop_per_node:     per node, triggered by the Excel "Stop application Group N" step.
  - stop_post_group:   once per group, after every node's stop_per_node has finished.
  - start_pre_group / start_per_node / start_post_group: mirror image, triggered by the
                       Excel "Start application Group N" step.

`splunk enable boot-start -systemd-managed 1 ...` is what (re)generates the systemd unit
file from a template - that's the "autogenerated" file that has to be overwritten with
the manually-edited copy afterward. So the start sequence is enable -> restore the edited
copy over it -> daemon-reload -> start, not restore-then-enable.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum

from auto_patchinator.actions.types import Action, ActionKind, ExpectStep, Identity

SPLUNK_BIN = "/opt/splunk/bin/splunk"
SPLUNK_BIN_INDEXER = "/splunkdata/splunk/bin/splunk"

SPLUNK_SERVICE_UNIT = "/etc/systemd/system/Splunkd.service"

# Shared scratch directory present on every node - used to stash the systemd unit file
# and crontab backups made during the stop half, restored during the start half.
APPLHOME_DIR = "/appl/home/splunk"
SPLUNK_SERVICE_UNIT_BACKUP = f"{APPLHOME_DIR}/Splunkd.service.copy"
CRONTAB_BACKUP = f"{APPLHOME_DIR}/crontab.backup"


class NodeRole(str, Enum):
    DEPLOYER = "deployer"
    INDEXER = "indexer"
    FORWARDER = "forwarder"
    SEARCH_HEAD_SIMPLE = "search_head_simple"
    SEARCH_HEAD_STRETCHED = "search_head_stretched"


SPLUNK_BIN_BY_ROLE = {role: SPLUNK_BIN for role in NodeRole} | {NodeRole.INDEXER: SPLUNK_BIN_INDEXER}


@dataclass(frozen=True)
class RoleSequences:
    stop_pre_group: tuple[Action, ...] = field(default_factory=tuple)
    stop_per_node: tuple[Action, ...] = field(default_factory=tuple)
    stop_post_group: tuple[Action, ...] = field(default_factory=tuple)
    start_pre_group: tuple[Action, ...] = field(default_factory=tuple)
    start_per_node: tuple[Action, ...] = field(default_factory=tuple)
    start_post_group: tuple[Action, ...] = field(default_factory=tuple)


# ---------------------------------------------------------------------------
# Building blocks shared by every role
# ---------------------------------------------------------------------------

def stop_splunk(splunk_bin: str) -> Action:
    return Action(
        name="stop_splunk",
        kind=ActionKind.PLAIN,
        identity=Identity.SPLUNK,
        command=f"sudo {splunk_bin} stop",
        timeout_seconds=900,  # a busy node can take well over the 60s default to shut down
    )


def start_splunk(splunk_bin: str) -> Action:
    return Action(
        name="start_splunk",
        kind=ActionKind.PLAIN,
        identity=Identity.SPLUNK,
        command=f"sudo {splunk_bin} start",
        timeout_seconds=900,  # first start after patching can be slow (migrations, preflight)
    )


def backup_unit_file() -> Action:
    return Action(
        name="backup_systemd_unit",
        kind=ActionKind.PLAIN,
        identity=Identity.ROOT,
        command=f"cp {SPLUNK_SERVICE_UNIT} {SPLUNK_SERVICE_UNIT_BACKUP}",
        note="Preserve the manually-edited unit file before disabling.",
    )


def disable_boot_start(splunk_bin: str) -> Action:
    return Action(
        name="disable_boot_start",
        kind=ActionKind.PLAIN,
        identity=Identity.SPLUNK,
        command=f"sudo {splunk_bin} disable boot-start",
        note="If this node's splunk user has no sudoers entry for this, rerun as root instead (no sudo).",
    )


def enable_boot_start(splunk_bin: str) -> Action:
    return Action(
        name="enable_boot_start",
        kind=ActionKind.PLAIN,
        identity=Identity.ROOT,
        command=f"{splunk_bin} enable boot-start -systemd-managed 1 -user splunk -group splunk",
        note="Regenerates the systemd unit file from a template - restore the edited copy right after this.",
    )


def restore_unit_file() -> Action:
    return Action(
        name="restore_systemd_unit",
        kind=ActionKind.PLAIN,
        identity=Identity.ROOT,
        command=f"cat {SPLUNK_SERVICE_UNIT_BACKUP} > {SPLUNK_SERVICE_UNIT}",
        note=(
            "Overwrite in place (cat >) rather than rm+cp: replacing the inode "
            "breaks systemd's cached unit state / file watch."
        ),
    )


def daemon_reload() -> Action:
    return Action(
        name="daemon_reload",
        kind=ActionKind.PLAIN,
        identity=Identity.ROOT,
        command="systemctl daemon-reload",
    )


def clean_kvstore(splunk_bin: str) -> Action:
    return Action(
        name="clean_kvstore",
        kind=ActionKind.PLAIN,
        identity=Identity.SPLUNK,
        command=f"{splunk_bin} clean kvstore --local",
    )


def backup_crontab() -> Action:
    return Action(
        name="backup_crontab",
        kind=ActionKind.PLAIN,
        identity=Identity.SPLUNK,
        command=f"crontab -l > {CRONTAB_BACKUP}",
        note="Save the current crontab BEFORE deleting it - enable_crontab restores from this file.",
    )


def disable_crontab() -> Action:
    return Action(
        name="disable_crontab",
        kind=ActionKind.INTERACTIVE,
        identity=Identity.SPLUNK,
        script=(
            ExpectStep(send="crontab -r", expect="really delete"),
            ExpectStep(send="yes"),
        ),
        note="splunk user's crontab is aliased to 'crontab -i', deletion needs confirmation.",
    )


def enable_crontab() -> Action:
    return Action(
        name="enable_crontab",
        kind=ActionKind.PLAIN,
        identity=Identity.SPLUNK,
        command=f"crontab {CRONTAB_BACKUP}",
        note="Restore the crontab saved by backup_crontab.",
    )


def wait(seconds: int, reason: str) -> Action:
    return Action(name=f"wait_{seconds}s", kind=ActionKind.WAIT, wait_seconds=seconds, note=reason)


def manual_todo(name: str, note: str) -> Action:
    """Placeholder for steps whose exact command is not known yet (flagged in the plan)."""
    return Action(name=name, kind=ActionKind.MANUAL, note=f"TODO: {note}")


# ---------------------------------------------------------------------------
# Role sequences
# ---------------------------------------------------------------------------

def _default_stop(splunk_bin: str) -> tuple[Action, ...]:
    return (stop_splunk(splunk_bin), backup_unit_file(), disable_boot_start(splunk_bin))


def _default_start(splunk_bin: str) -> tuple[Action, ...]:
    return (enable_boot_start(splunk_bin), restore_unit_file(), daemon_reload(), start_splunk(splunk_bin))


def deployer_sequences() -> RoleSequences:
    return RoleSequences(stop_per_node=_default_stop(SPLUNK_BIN), start_per_node=_default_start(SPLUNK_BIN))


def indexer_sequences() -> RoleSequences:
    # S&R factor wait/check after restart is deferred to v2 - see project plan.
    return RoleSequences(
        stop_per_node=_default_stop(SPLUNK_BIN_INDEXER),
        start_per_node=_default_start(SPLUNK_BIN_INDEXER),
    )


def search_head_simple_sequences() -> RoleSequences:
    # No KVStore clean and no captain handling for the 3-node extra cluster.
    return RoleSequences(stop_per_node=_default_stop(SPLUNK_BIN), start_per_node=_default_start(SPLUNK_BIN))


def captain_transfer_static(other_site_label: str) -> Action:
    """Manual step injected once before the first stretched-SH stop in a wave."""
    return manual_todo(
        "transfer_captain_static",
        "Cluster-wide, before touching this site: on the chosen new captain (a host on "
        f"{other_site_label}, the site NOT being patched) run "
        f"`{SPLUNK_BIN} edit shcluster-config -mode captain "
        "-captain_uri https://<new-captain-host>.sky.local:8089 -election false`; then on every "
        "OTHER search head in the whole cluster (both sites) run "
        f"`{SPLUNK_BIN} edit shcluster-config -mode member "
        "-captain_uri https://<new-captain-host>.sky.local:8089 -election false` "
        "(as the splunk user).",
    )


def captain_revert_dynamic() -> Action:
    """Manual step injected once after the last stretched-SH start in a wave."""
    return manual_todo(
        "revert_captain_dynamic",
        "Once all nodes on this site are fully back up: on every member except the current "
        "captain, then lastly on the captain itself, run "
        f"`{SPLUNK_BIN} edit shcluster-config -election true "
        "-mgmt_uri https://<that-node>.sky.local:8089`; then from the captain run "
        f"`{SPLUNK_BIN} bootstrap shcluster-captain -servers_list \"https://<host1>.sky.local:8089,"
        "...\" -auth admin:<password>` - DO NOT hardcode the admin password anywhere in this "
        "repo or commit history; type it only at the live terminal.",
    )


def search_head_stretched_sequences() -> RoleSequences:
    # Captain transfer/revert are injected once per wave (first stop / last start)
    # by build_run_plan, not repeated per group.
    return RoleSequences(
        stop_per_node=_default_stop(SPLUNK_BIN),
        start_per_node=(
            *_default_start(SPLUNK_BIN),
            clean_kvstore(SPLUNK_BIN),
        ),
    )


def forwarder_sequences() -> RoleSequences:
    return RoleSequences(
        stop_per_node=(backup_crontab(), disable_crontab(), *_default_stop(SPLUNK_BIN)),
        start_per_node=(*_default_start(SPLUNK_BIN), enable_crontab()),
    )


# ---------------------------------------------------------------------------
# Per-host overrides - keyed by hostname, take precedence over the role default.
# ---------------------------------------------------------------------------

def _prdmilbbspkfw02_sequences() -> RoleSequences:
    return RoleSequences(
        stop_per_node=(
            backup_crontab(),
            disable_crontab(),
            wait(180, "Allow in-flight cron jobs to finish before touching StreamSets."),
            manual_todo("disable_streamsets_pipelines", "Disable the StreamSets pipelines on this node."),
            *_default_stop(SPLUNK_BIN),
        ),
        start_per_node=(
            *_default_start(SPLUNK_BIN),
            manual_todo("enable_streamsets_pipelines", "Re-enable the StreamSets pipelines on this node."),
            enable_crontab(),
        ),
    )


HOST_OVERRIDES = {
    "prdmilbbspkfw02": _prdmilbbspkfw02_sequences,
}

# Hosts where the splunk-level identity cannot be used over SSH at all; every action that
# needs Identity.SPLUNK on these hosts is forced to MANUAL by the executor/run controller.
# Previously prdrmlbbspksh01 and prdrmlbbspkdp01 were listed here, but those are now
# reachable via PAS port 10100 (set in inventory as pas_port: 10100) - not manual-only.
MANUAL_ONLY_IDENTITIES: dict[str, tuple[Identity, ...]] = {}


ROLE_SEQUENCES = {
    NodeRole.DEPLOYER: deployer_sequences,
    NodeRole.INDEXER: indexer_sequences,
    NodeRole.FORWARDER: forwarder_sequences,
    NodeRole.SEARCH_HEAD_SIMPLE: search_head_simple_sequences,
}


def splunk_bin_for(role: NodeRole) -> str:
    return SPLUNK_BIN_BY_ROLE[role]


def get_role_sequences(hostname: str, role: NodeRole) -> RoleSequences:
    if hostname in HOST_OVERRIDES:
        return HOST_OVERRIDES[hostname]()
    if role == NodeRole.SEARCH_HEAD_STRETCHED:
        return search_head_stretched_sequences()
    return ROLE_SEQUENCES[role]()
